### ISSUE TITLE
Invalid dependency on cryptohash-sha256-pure

### ISSUE THREAD

**Issue by peti** [hvr/cryptohash-sha256#11]
The current version on Hackage has an (optional?) dependency on `cryptohash-sha256-pure`, but no such Haskell package exists on Hackage. Is that intentional?

**Comment by phadej** [comment]
It's probably an oversight to require it in benchmarks, I removed it for now https://github.com/haskell-hvr/cryptohash-sha256/pull/14

**Comment by phadej** [comment]
https://hackage.haskell.org/package/cryptohash-sha256-0.11.102.1 released
