### ISSUE TITLE
problematic on 32-bit mips and mipsel with GHC 8.2.2

### ISSUE THREAD

**Issue by clinty** [hvr/cryptohash-sha256#3]
test-sha256 goes into an infinite loop of

    `test-sha256: lost signal due to full pipe: 11`

Aside from that, hackage-security built with this library also fails

**Comment by clinty** [comment]
Sometimes this is

`test-sha256: lost signal due to full pipe: 10`

**Comment by hvr** [comment]
Sorry, totally missed the notification. I don't remember right now; does Debian on `mips` have any special requirements regarding data-alignment? What kind of GHC is used on mips? registerised? NCG?

There's a chance that I made some assumptions in the FFI parts that don't hold for `mips`.

**Comment by clinty** [comment]
Let me know if https://wiki.debian.org/Haskell/GHC and https://wiki.debian.org/ArchitectureSpecificsMemo don't answer your questions.

**Comment by adamgundry** [comment]
For posterity, this might be related to a GHC RTS issue: https://gitlab.haskell.org/ghc/ghc/issues/15544

**Comment by hvr** [comment]
Thanks for the reminder; I'll close this hoping that it was indeed fixed with GHC 8.6.1+ -- it's still a bit unsatisfying though there might be segfault potential lurking in GHC < 8.6 releases out there... :-/
